
<div class="card border-<?php echo  ($group->status) ? 'success' : 'warning'; ?>">
    <div class="card-header text-center bg-<?php echo  ($group->status) ? 'success text-white' : 'warning text-dark'; ?>"
         onclick="bodyDisplay('<?php echo $group->externalNumber;?>');">
        <img id="<?php echo $group->externalNumber;?>_img" src="img/closed.png"
             height="32" width="32"><?php echo  $group->externalNumber; ?>
    </div>
    <div class="card-body" style="display: none" id="<?php echo $group->externalNumber;?>">
        <table class="table table-bordered table-hover small border-dark"
               style="line-height: 0.9rem">
            <tr>
                <th>Время звонка</th>
                <th>А номер</th>
                <th>Внешний номер</th>
                <th>Б номер</th>
                <th>Длительность</th>
                <th>Запись</th>
            </tr>
        <?php foreach ($group->calls as $call):?>
        <tr class="alert alert-<?php echo  ($call->status) ? 'success': 'warning'; ?>">
            <td><?php echo  $call->calldate; ?></td>
            <td><?php echo  $call->srcNumber; ?></td>
            <td><?php echo  $call->did; ?></td>
            <?php if ($call->status):?>
                <td><?php echo  $call->dstNumber; ?></td>
                <td><?php echo  gmdate("i:s", $call->duration); ?></td>
                <td>
                    <?php if ($call->recordingfile): ?>
                    <a target="_blank" href="<?php echo $call->recordingfile;?>">
                    <img src="img/play.png"
                         height="16" width="16">
                    </a>
                    <?php endif; ?>
                </td>
            <?php else: ?>
                <td><?php echo  implode(', ', array_unique($call->dstlist)); ?></td>
                <td><?php echo  gmdate("i:s", 0); ?></td>
                <td></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>